name: jst_data
description: JuShuiTan Data.
version: 0.1.4
repository: https://github.com/hestia-io/jst_data


environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.13.1
  crypto: ^3.0.0
  uniform_data: ^0.1.1
    #uniform_data: 
    #path: ../uniform_data 
  logging: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8  
  mockito: ^5.0.3
